### ISSUE TITLE
RsaUsingSha alg expects key to be of RSA type.

### ISSUE THREAD

**Issue by newbie1416** [Nexmo/nexmo-dotnet#91] opened 2018-03-09 16:46 UTC
Hi,

I tried to make a call and got an error message below.

System.ArgumentException
  HResult=0x80070057
  Message=RsaUsingSha alg expects key to be of RSA type.
  Source=jose-jwt
  StackTrace:
   at Jose.Ensure.Type[T](Object obj, String msg, Object[] args)
   at Jose.RsaUsingSha.Sign(Byte[] securedInput, Object key)
   at Jose.JWT.EncodeBytes(Byte[] payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders, JwtSettings settings)
   at Jose.JWT.Encode(String payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders, JwtSettings settings)
   at Jose.JWT.Encode(Object payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders, JwtSettings settings)
   at Nexmo.Api.Jwt.CreateToken(String appId, String privateKey)
   at Nexmo.Api.Request.VersionedApiRequest.DoRequest(String method, Uri uri, Object payload, Credentials creds)
   at Nexmo.Api.Voice.Call.Do(CallCommand cmd, Credentials creds)

**Comment by smithrobs** [comment] 2018-03-12 12:10
Hi! If you are using v3.0+ of this library, the first thing to check is that you are providing the **full contents** of your keyfile instead of the path to the keyfile.

> [BREAKING] ApplicationKey must now be the actual private key and not a path to the key.

If you are not using v3.0+ or you are passing in the contents of the keyfile, please let me know the version of the library you are using, the .NET and/or netcore version you are targeting, and OS.

**Comment by newbie1416** [comment] 2018-03-14 02:23
Hi Rob,
when I use the full contents of the key file, I got an error message below.

System.NotSupportedException
  HResult=0x80131515
  Message=Encrypted key not supported
  Source=Nexmo.Api
  StackTrace:
   at Nexmo.Api.PemParse.DecodeOpenSSLPrivateKey(String instr)
   at Nexmo.Api.PemParse.DecodePEMKey(String pemstr)
   at Nexmo.Api.Jwt.CreateToken(String appId, String privateKey)
   at Nexmo.Api.Request.VersionedApiRequest.DoRequest(String method, Uri uri, Object payload, Credentials creds)
   at Nexmo.Api.Voice.Call.Do(CallCommand cmd, Credentials creds)

Thanks,

Henry

**Comment by smithrobs** [comment] 2018-04-01 12:42
What is the version of the library you are using, the .NET and/or netcore version you are targeting, and OS?

A few things to try in the meantime:
- Generate a new application and key and try with the new key.
- Be careful of how you save and "maintain" your keyfiles. Example: Editors can change the byte order mark which can cause the PEM loader to fail.

**Comment by arrebagrove** [comment] 2018-05-29 07:39
@smithrobs I have the same issue on UWP running visual studio 15.7.2 on windows 10 version 1803 and .net 4.6.1

Exception thrown: 'System.ArgumentException' in jose-jwt.dll
An exception of type 'System.ArgumentException' occurred in jose-jwt.dll but was not handled in user code
RsaUsingSha alg expects key to be of RSA type.

**Comment by JerseyTechGuy** [comment] 2018-07-18 13:50
I just fought with this issue myself.  Not well documented and even Nexmo Support was stumped even thought they claim to know their libraries well.  To keep our configurations as they were, I simply added a File.ReadAllText(<filepath>) to load the contents of the file into the application key.  Worked perfectly.

**Comment by skandyrocks** [comment] 2018-08-08 13:07
I also have the same exception. I am on Mac OS. here is my code:
```
var privateKey = File.ReadAllText("private.key");

Call.Edit(callId,
    new Call.CallEditCommand
    {
        action = "transfer",
        destination = new NexmoDestination
        {
            Url =
                $"https://{Startup.Config["NgrokId"]}.ngrok.io/api/nexmo/handover?callId={callId}&from={from}"
        }
    },
    new Credentials
    {
        ApiKey = "api_key",
        ApiSecret = "api_secret",
        ApplicationId = "applicationId",
        ApplicationKey = privateKey
    });
```

what am I doing wrong?

**Comment by skandyrocks** [comment] 2018-08-14 10:15
as I did not expect an answer here anymore I fixed that bug by myself.
@smithrobs in `PemParse.cs: line 259' use RSA = RSA.Create(). otherwise it will throw a `PlatformNotSupportedException` on Linux and MacOS

Additionally I want to say that the .net library is in a bad shape. Barely any unit tests and not tested on more than one platform. Also the code style is not good!

**Comment by RabebOthmani** [comment] 2018-08-14 11:34
Hi @skandyrocks ,
Thank you for your feedback and I'm sorry you had a bad experience with the Client Lib. 
It's an ongoing work in progress and is constantly improving.

**Comment by smithrobs** [comment] 2018-08-14 11:55
@skandyrocks I replied to you in the Nexmo Slack with no reply.

There are tests (minimal as they are); I exercise them on all three platforms before releasing. As Bibi said, we're always working on the library (it's over 3 years old now and has been through many versions, .NET Core support, etc.) and regularly engage with the community to make your job easier and the library better.

Re: your platform exception - this was a known bug with netstandard2.0 that was addressed in February. If you continue to receive this bug with latest (either 3.0.1 or 3.1.0-rc) please file a separate issue and we will investigate. PemParse is working for win, mac, osx with 3.0.1 and 3.1.0-rc.

**Comment by skandyrocks** [comment] 2018-08-14 12:57
@smithrobs your response on slack was

> I just replied to your issue on github. Thank you for the additional code snippets.
> `NexmoDestination` is your code, correct?

so I answered you on GitHub. Should I answer you in Slack when you answered me on GitHub? Maybe I did a mistake there...

> Re: your platform exception - this was a known bug with netstandard2.0 that was addressed in February.

I am on netcoreapp2.1 and if you take a look into the implementation of the `RSACng`-constructor you'll find this:
```
public RSACng()
{
  throw new PlatformNotSupportedException(SR.PlatformNotSupported_CryptographyCng);
}
```
So your code isn't working for .net core atm

**Comment by smithrobs** [comment] 2018-08-14 13:15
No worries; it's tough to convey intent on the internet sometimes. 😄I wanted to confirm that `NexmoDestination` was your code as I noticed the same thing you did - the `CallEditCommand` structure did not look correct. We will address that in 3.1.0, thank you.

Hm, netcoreapp2.1... yes, to be honest we haven't tested 2.1 at all yet - we try to keep the [targeted frameworks](https://github.com/Nexmo/nexmo-dotnet#targeted-frameworks) list in the README up-to-date. In theory it should work as we target netstandard1.6 and 2.0. I wonder if `RuntimeInformation.IsOSPlatform` isn't reporting as expected for some reason. (https://github.com/Nexmo/nexmo-dotnet/blob/master/Nexmo.Api/PemParse.cs#L245)

Let me create a quick netcoreapp2.1 app here and see if I can reproduce.

**Comment by a-patel** [comment] 2018-08-20 17:13
Any update?
I am also getting the same error.

**Comment by a-patel** [comment] 2018-08-20 17:28
Hi @smithrobs 
ApplicationId and ApplicationKey are required?

If yes, 
Where do I get them?

**Comment by smithrobs** [comment] 2018-08-21 16:43
@a-patel They are required for voice, yes. 

You can create an application and retrieve them for your newly created application from your [Nexmo account dashboard](https://dashboard.nexmo.com/voice/getting-started). Alternatively you can use the Nexmo CLI or this library itself to programmatically create and maintain your Nexmo applications.

**Comment by a-patel** [comment] 2018-08-21 17:03
@smithrobs 
I have created the application in voice call section.
I get the ApplicationId but I didn't find the ApplicationKey (is this user has to create manually? if yes then I have created it)

But still getting the same error in the voice call.

**Comment by a-patel** [comment] 2018-08-21 19:10
@smithrobs 
Still, no luck, getting the same.
FYI - I am using trial.

**Comment by smithrobs** [comment] 2018-08-21 20:32
@a-patel Would you mind either [filing a support request](https://help.nexmo.com/hc/en-us/requests/new) directly to Nexmo or asking in the [Nexmo Slack](https://developer.nexmo.com/community/slack)? This library has no control over the issue if Nexmo does not accept your API calls due to account/billing issues. You will receive a better experience regarding troubleshooting your specific account.

**Comment by a-patel** [comment] 2018-08-22 04:56
@smithrobs 
Thanks.

**Comment by BloomBitz** [comment] 2018-08-30 08:00
Where cani can find the path of my private key?

**Comment by skandyrocks** [comment] 2018-08-30 08:09
@BloomBitz when you create a new application with the nexmo dashboard or cli nexmo creates a public-/private-key pair. You should save the private key anywhere on your computer. No one can tell you how to find that path ;)

With the newer API versions (I think 3+) you do not have to provide the path to the private key. You need to provide the content of the private key:

`var contentOfPrivateKey = File.ReadAllText("pathToPrivateKey.key");`

Hope that helps

**Comment by BloomBitz** [comment] 2018-08-30 08:16
Thanku i did this .
Can you tell me one thing that without buying any number from my nexmo
account, can i do outbound calls through Test Numbers?

**Comment by BloomBitz** [comment] 2018-08-30 10:51
can you tell me how to make dynamic ncco in asp.net

**Comment by RabebOthmani** [comment] 2019-02-19 12:40
Closing this issue as it's been taken care of on our community slack

**Closed by RabebOthmani** 2019-02-19 12:40 UTC
Labels: question

**Comment by Unders0n** [comment] 2019-06-19 15:52
i think your docs should be updated (dotnet atleast) , they still refferencing path to file instead of cert itself
