### ISSUE TITLE
System.TypeInitializationException

### ISSUE THREAD

**Issue by Nidiginti** [Nexmo/nexmo-dotnet#75] opened 2017-12-13 04:51 UTC
while trying to send sms on button click 

the code written is 

 SMS.Send(new SMS.SMSRequest
        {
            from = "XXXXXXXXXX",
            to = "+91XXXXXXXXX",
            text = "A text message sent using the Nexmo SMS API"
        });

web.config
 <appSettings>
    <add key="Nexmo.UserAgent" value="myApp/1.0"/>
    <add key="Nexmo.Url.Rest" value="https://rest.nexmo.com"/>
    <add key="Nexmo.Url.Api" value="https://api.nexmo.com"/>
    <add key="Nexmo.api_key" value=""/>
    <add key="Nexmo.api_secret" value=""/>
  </appSettings>

**Comment by smithrobs** [comment] 2017-12-13 15:59
Are you using v2.x or v3.x of the library? What is the trust level you are executing under? This could be a dupe of #32 - take a look at that first and let us know.

**Comment by Nidiginti** [comment] 2017-12-14 04:26
I am using v2.X library and the trust level is full

**Comment by Nidiginti** [comment] 2017-12-14 06:33
Now i have tried with the version v3.x library and in web config  i have used apikey ,apisecret and trust level is 'Full'  but still showing null pointer exception.

ok i have tried my code using URL.  The sms has sent

 string TranUrl = " https://rest.nexmo.com/sms/xml?api_key=f1d90c5e&api_secret=30ad3ed2d702e1bf&from=CEOVOC&to=+91xxxxxxxxx&text=Testingsms";

can we use this method to send the sms?can you clarify?or any other alternate?

**Comment by smithrobs** [comment] 2017-12-14 13:03
This library is for your convenience and is not required. You can always make a HTTP request without the use of this library or any other library. [developer.nexmo.com](https://developer.nexmo.com/) contains all the information users need to use the API.

I see you continue to have trouble but unfortunately I cannot do much without a full stack trace. For the original v2.x issue I am unsure why you received a `System.TypeInitializationException` when sending an SMS. If you are running in full trust then permissions should not be a problem.

For the v3.x issue you mentioned using `web.config` which is no longer directly supported. You must pass your credentials to the static or instance method that you call. Something like this:

```csharp
using Nexmo.Api;
using Nexmo.Api.Voice;

            var creds = new Nexmo.Api.Request.Credentials {
                ApiKey = "YOUR_KEY",
                ApiSecret = "YOUR_SECRET",
                ApplicationId = "YOUR_APP_GUID",
                ApplicationKey = "PATH_TO_PRIVATE_KEY"
            };
            var client = new Nexmo.Api.Client(creds);
            client.SMS.Send(new SMS.SMSRequest{
                from = "<SOURCE #>",
                to = "<DESTINATION #>",
                text = "hey there!"
            });

// or static
            SMS.Send(new SMS.SMSRequest{
                from = "<SOURCE #>",
                to = "<DESTINATION #>",
                text = "hey there!!!"
            }, creds);
```

The documentation for v3.x isn't clear on this; we will incorporate these examples before the official release.

**Comment by Nidiginti** [comment] 2017-12-15 04:56
Thank you for your code its working.How can i get the XML file in which it contains message status.

**Comment by Nidiginti** [comment] 2017-12-18 10:37
can anyone tell the packages for SMS in USA.And what is the price for buying long virtual number??Is there any validity for packages.

**Comment by smithrobs** [comment] 2018-02-24 02:53
> How can i get the XML file in which it contains message status. 

You are probably looking for a [delivery receipt](https://developer.nexmo.com/messaging/sms/guides/delivery-receipts) - there's a quick example [here](https://github.com/Nexmo/nexmo-dotnet#receiving-a-message-delivery-receipt).

For general support questions I recommend the official [Nexmo Slack](https://developer.nexmo.com/community/slack), opening a [support request](https://help.nexmo.com/hc/en-us/requests/new), or emailing support@nexmo.com.

**Closed by smithrobs** 2018-02-24 02:53 UTC
Labels: question
