### ISSUE TITLE
Value cannot be null errror

### ISSUE THREAD

**Issue by HStuart18** [Nexmo/nexmo-dotnet#134] opened 2018-12-27 16:45 UTC
I am trying to begin a call to a phone number in ASP.NET MVC Core. However, the following code is producing the error `Value cannot be null`:

    Client nexmoClient = new Client(new Credentials
    {
        ApiKey = "...",
        ApiSecret = "...",
        ApplicationId = "...",
        ApplicationKey = File.ReadAllText(@"C:\Users\...\data\nexmoPrivateKey.key")
    });

    nexmoClient.Call.Do(new Call.CallCommand
        {
            to = new[]
            {
                new Call.Endpoint {
                    type = "phone",
                    number = "61400..."
                }
            },
            from = new Call.Endpoint
            {
                type = "phone",
                number = "61290..."
            },
            answer_url = new[]
            {
                "https://nexmo-community.github.io/ncco-examples/first_call_talk.json"
            }
        });
**UPDATE**

Even using a static NCCO provided in the documentation, I get the error `value cannot be null` while trying to make an outbound call.

Thanks!

**Comment by slorello89** [comment] 2020-02-07 15:40
#187 will make these errors more explicit - essentially this means the status received back from the Nexmo API was not successful - most likely due to a bad private key.

**Comment by evi-pparedes** [comment] 2020-03-20 13:01
Hi, we've been facing the same issue on version 4.3.1. It seems that, indeed, the problem is with the application ID as the same error occurs when I try to send an invalid ID.
Are there any new insights on this error?
It would be very bad if we'd have to create a new voice application any time this issue arises.

Thank you for your time.

**Comment by slorello89** [comment] 2020-03-20 13:12
Hi @evi-pparedes - so the first thing I would do is to enable `Nexmo.Api.EnsureSuccessStatusCode` in your configuration - that will force the Http exception to show itself - in the next major release I'll be making the errors a lot more explicit. If what you're seeing is a 401 - bad credentials - then you likely have a bad private key/appId combo that you're using. Go to your dashboard and open the application, edit it, generate a new public/private key pair, and make sure you click **_save_** - it gets a lot of people.

**Comment by slorello89** [comment] 2020-06-22 13:52
Hello all who were running into this issue - the "Value Cannot be Null" was just bad error reporting coming off of the SDK. We've Just pushed a new update where errors encountered like these will continue to throw exceptions - however they will be typed exceptions and they will describe what the issue is for your debugging. I am closing this out as it should e resolved. If you continue to experience issues you're unable to diagnose feel free to reopen.

**Closed by slorello89** 2020-06-22 13:52 UTC
Labels: question
