### ISSUE TITLE
Add support for file/recording retrieval

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-dotnet#113] opened 2018-09-17 12:24 UTC
### General description of the issue or question

Add support to retrieve calls to the .NET library. For the Nexmo Node library this looks like:

```js
nexmo.files.get(fileIdOrUrl, callback)
```

Where `fileIdOrUrl` is the UUID for the file to be retrieved or the URL for the file.

**Comment by RabebOthmani** [comment] 2019-01-23 12:55
Closing as this issue is a duplicate of https://github.com/Nexmo/nexmo-dotnet/issues/44

**Closed by RabebOthmani** 2019-01-23 12:55 UTC
Labels: duplicate, enhancement
