### ISSUE TITLE
Getting an Error while setting event_url and event_method in NCCO using Nexmo.Csharp.Client -Version 3.2.4

### ISSUE THREAD

**Issue by AECDev11** [Nexmo/nexmo-dotnet#147] opened 2019-02-20 12:06 UTC
Hi,

We are using Nexmo.Csharp.Client -Version 3.2.4 to develop an application to make an call but we are 
getting following error  while setting event_url 

   at Jose.Ensure.Type[T](Object obj, String msg, Object[] args)
   at Jose.RsaUsingSha.Sign(Byte[] securedInput, Object key)
   at Jose.JWT.EncodeBytes(Byte[] payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders, JwtSettings settings)
   at Jose.JWT.Encode(String payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders, JwtSettings settings)
   at Jose.JWT.Encode(Object payload, Object key, JwsAlgorithm algorithm, IDictionary`2 extraHeaders, JwtSettings settings)
   at Nexmo.Api.Jwt.CreateToken(String appId, String privateKey)
   at Nexmo.Api.Request.VersionedApiRequest.DoRequest(String method, Uri uri, Object payload, Credentials creds)
   at Nexmo.Api.Voice.Call.Do(CallCommand cmd, Credentials creds)

Sample code 
Call.CallResponse callResponse = client.Call.Do(new Call.CallCommand
                {
                    to = new[]
                    {
                        new Call.Endpoint {
                            type = "phone",
                            number = toNumber
                        }
                    },
                    from = new Call.Endpoint
                    {
                        type = "phone",
                        number = fromNumber
                    },
                    answer_url = new[]
                    {
                        answerURL
                    },
                    answer_method = "POST",
                    event_url = new[]
                    {
                        EventURL
                    },
                    event_method = "POST",
                    machine_detection = "continue"

                });
Please help us on this 
Thanks,

**Comment by slorello89** [comment] 2020-02-05 13:35
Hi @AECDev11 

I'm pretty sure this is a duplicate of: https://github.com/Nexmo/nexmo-dotnet/issues/154 - can you try to load the newest version (4.3.0) and see if you are still encountering this issue.

thanks

**Comment by slorello89** [comment] 2020-04-08 15:55
Hi @AECDev11  - going to close this out as I haven't heard back from you - if this is still an issue please reopen the issue - thanks!

**Closed by slorello89** 2020-04-08 15:55 UTC
