### ISSUE TITLE
Search.GetMessage => Unexpected character encountered while parsing value 

### ISSUE THREAD

**Issue by cleverkom-twarnick** [Nexmo/nexmo-dotnet#127] opened 2018-10-25 17:42 UTC
Unexpected character encountered while parsing value: <. Path '', line 0, position 0
--

### Which target framework(s) of .NET can you reproduce this issue against?
.NET Framework 4.6.2

### What operating system(s) is exhibiting this issue?
Windows 10

### Version or commit hash
CSharp.Nexmo.Client version: 3.2.2

### Expected Behavior
return SMS Message

### Actual Behavior
Exception:
Unexpected character encountered while parsing value: <. Path '', line 0, position 0., Stack:   bei Newtonsoft.Json.JsonTextReader.ParseValue()
   bei Newtonsoft.Json.JsonTextReader.Read()
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bei Nexmo.Api.Search.GetMessage(String id, Credentials creds)
   bei Nexmo.Api.ClientMethods.Search.GetMessage(String id, Credentials creds)

### Steps to Reproduce
	Credentials cred = new Credentials();
	cred.ApiKey = "yyy";
	cred.ApiSecret = "xxx";
	
	Client client = new Client(cred);
	var xx = client.Search.GetMessage("0B000000282160C7");
	
	try
	{	        
		var xxx = client.Search.GetMessage("0C00000000EAFFC0");
	}
	catch (Exception ex)
	{
		Console.WriteLine($"Msg:{ex.Message}, Stack:{ex.StackTrace}");
	}

**Comment by cleverkom-twarnick** [comment] 2018-10-25 17:45
The content of the message is:
AT$GPRS=4464,1,&#034;internet.m2mportal.de&#034;,&#034;m2m&#034;,&#034;sim&#034; ... 
So this could be the reason.

**Comment by judy2k** [comment] 2019-02-19 14:44
It looks like this is attempting to parse XML data as JSON.

**Comment by slorello89** [comment] 2020-02-07 15:22
Hi @cleverkom-twarnick - just tried to reproduce this with the message that you mentioned - I think this may have been resolved in one of the later releases of the SDK - I am not having this issue - can you confirm?

**Comment by slorello89** [comment] 2020-02-24 15:19
Hi @cleverkom-twarnick - As I'm not able to reproduce I'm going to assume this issue was resolved - I'm going to close it out - feel free to reopen if you encounter the issue again with the latest SDK.

thanks,

**Closed by slorello89** 2020-02-24 15:19 UTC
Labels: bug
