### ISSUE TITLE
Implement `submitConversion`

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-dotnet#43] opened 2017-08-21 12:17 UTC

**Comment by smithrobs** [comment] 2017-08-21 12:21
Spec is [https://developer.nexmo.com/api/conversion](here).

**Comment by RabebOthmani** [comment] 2019-01-23 12:53
Closing as this issue is a duplicate of https://github.com/Nexmo/nexmo-dotnet/issues/136 cc @judy2k

**Closed by RabebOthmani** 2019-01-23 12:53 UTC
Labels: duplicate
